### ISSUE TITLE
Running am from within chroot - no results 

### ISSUE THREAD

**Issue by ronnac** [michalbednarski/TermuxAm#3]
On my Galaxy J5 nougat I am using Neo-Oli's Ubuntu for termux. Starting an app with "am start" from termux works fine, however when I do it from within the Ubuntu chroot, it gives no result,  not even an error.
I had done the same earlier on a different phone (LG4) with no problem (I had to bind the system and the vendor folders and use the env command to make it work:                         
env -i PATH=/data/data/com.termux/files/usr/bin ANDROID_DATA=/data am ....).
I put some "echo test" in the am.sh script and they get printed to the terminal, until the last line, when the script calls the termuxam.apk . What would be the next step for debugging. Re-compile termuxam and write to logcat?

**Comment by michalbednarski** [comment]
See termux/termux-api#140

**Comment by ronnac** [comment]
That unblocked me. I had to bind /property_contexts and then it worked. I had already bound all the other folders. 

Dziękuję
